### ISSUE TITLE
Player names being corrupted (sometimes)

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/octane#18]
I've been working on a new RLR feature using 0.10.0 and I've been seeing some weirdness around [this replay](https://www.rocketleaguereplays.com/replays/5a093209-454e-165f-d629-71ac44c92c48/).  Both players have simple UTF-8 names, but I'm seeing data like this:

```
"Engine.PlayerReplicationInfo:PlayerName": {
    "Value": "Âv¦¶",
    "Type": "String"
},
```

```
"Engine.PlayerReplicationInfo:PlayerName": {
  "Value": "F¦¦æ¦",
  "Type": "String"
},
```

The same names in the metadata are appearing correctly, but in the frames they're garbled.

**Comment by tfausak** [comment]
I must be parsing text incorrectly in the frames. I'm doing it right in the metadata, which is why their names are okay there. I'll bet the bits have to be flipped just like everything else.
