### ISSUE TITLE
Feature request: Accept URLs as inputs

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/octane#19]
At the moment I have to do a lot of annoying wgets / temp file storing / file cleanup to pass my replay files into Octane (I have worker servers which run the executables, the files are on S3), so it would be really great if I could just pass in the URL for the files.

**Comment by tfausak** [comment]
Seems reasonable. This would also make it easier to see what Octane spits out for any given replay. All you'd need to do is `octane media.rocketleaguereplays.com/...`.
