### ISSUE TITLE
Feature request: Decode PSN usernames

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/octane#30]
It appears that PSN usernames are being output in their encoded format, which is extremely trivial to decode.  Given the following output from [this replay](https://www.rocketleaguereplays.com/replays/a9e57968-4164-7ccd-1f98-63badac57a68/):

```
"Engine.PlayerReplicationInfo:UniqueId": {
  "Value": {
    "Remote": "476c6f7773426c75650000000000000062376762707334000100000000000000",
    "Local": 0,
    "System": "PlayStation"
  },
  "Type": "UniqueId"
},
```

Take the first 32 characters of the `Remote` key and hex decode them:

`476c6f7773426c756500000000000000` -> GlowsBlue

**Comment by tfausak** [comment]
Sounds easy enough! I'll look at updating [the parser](https://github.com/tfausak/octane/blob/dd9ca40cfa3b5e676be914c6250ae3f193662b75/library/Octane/Utility/Parser.hs#L576-L585) to handle this.
