### ISSUE TITLE
Invalid Steam ID being output

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/octane#38]
I'll preface this by saying that it could just be the replay itself that is wrong, but I thought you'd be interested none-the-less.

On [this](https://www.rocketleaguereplays.com/replays/c9bd8011-4967-696b-a792-e8bd905f8ada/) replay, the player with the name 'Ahad' has a Steam ID set to a value of 24488897, which is not a valid Steam ID.

```
"Engine.PlayerReplicationInfo:UniqueId": {
  "Value": {
    "Remote": {
      "Value": 24488897,
      "Type": "Steam"
    },
    "Local": 0,
    "System": "Steam"
  },
  "Type": "UniqueId"
},
```

Is this a replay error, or a parser issue?

**Comment by tfausak** [comment]
Seems like a bug. Do you know what the Steam ID should be?

**Comment by tfausak** [comment]
[SteamIDs](https://developer.valvesoftware.com/wiki/SteamID) are more complicated than I assumed. They are serialized like this:
- 8 bits of the universe
- 4 bits of the type
- 20 bits of the instance
- 32 bits of the actual ID
