### ISSUE TITLE
Don't know how to read property "TAGame.PRI_TA:PawnType"

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/octane#39]
I've been seeing this one fairly often lately. Here are some example replays:
- [RLCS GS2: TFD vs SA 1
  ](https://www.rocketleaguereplays.com/replays/dcb3a6b9-4a9d-be46-fde5-eaa9b012f6c8/)
- [RLCS GS2: TFD vs SA 2
  ](https://www.rocketleaguereplays.com/replays/a31364f6-4d26-79ba-08a0-29ba59cbb42d/)
- [RLCS GS2: TFD vs SA 3
  ](https://www.rocketleaguereplays.com/replays/8933e837-4c2d-8836-5889-189bb04303b3/)
- [RLCS GS2: TFD vs SA 4](https://www.rocketleaguereplays.com/replays/86ef6c91-4bd6-91af-16af-2eafc878cde9/)
- [RLCS GS2: TFD vs SA 5
  ](https://www.rocketleaguereplays.com/replays/2474e0f5-47b6-c8be-4b73-30814fdb40d2/)

There's a whole load more in [this replay pack](https://www.rocketleaguereplays.com/replay-packs/227/) too, roughly half of the replays fail to parse.

The stack trace I have is this:

```
octane-0.13.0-osx: Data.Binary.Get.runGet at position 1066: Don't know how to read property "TAGame.PRI_TA:PawnType"
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
```

**Comment by tfausak** [comment]
Ah, those lovely Haskell "stack traces". I'll take a look at this soon.

**Comment by tfausak** [comment]
Not that it's any more useful, but here's a complete stack trace:

```
> stack exec octane https://media.rocketleaguereplays.com/uploads/replay_files/DCB3A6B94A9DBE46FDE5EAA9B012F6C8.replay
octane: Data.Binary.Get.runGet at position 1088: Don't know how to read property "TAGame.PRI_TA:PawnType"
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
CallStack (from -prof):
  Octane.Utility.Parser.parseStream.(...) (library/Octane/Utility/Parser.hs:59:5-49)
  Octane.Utility.Parser.parseStream (library/Octane/Utility/Parser.hs:(49,1)-(60,13))
  Octane.Type.ReplayWithFrames.fromReplayWithoutFrames (library/Octane/Type/ReplayWithFrames.hs:(64,1)-(80,9))
  Octane.Type.ReplayWithFrames.get (library/Octane/Type/ReplayWithFrames.hs:(50,5)-(52,51))
  Octane.Type.OptimizedReplay.get (library/Octane/Type/OptimizedReplay.hs:(54,5)-(56,45))
  Octane.Type.Replay.get (library/Octane/Type/Replay.hs:(83,5)-(85,43))
  Octane.Main.decode.replay (library/Octane/Main.hs:76:17-44)
  Octane.Main.decode (library/Octane/Main.hs:(67,1)-(77,23))
  Octane.Main.main1 (library/Octane/Main.hs:(53,1)-(56,27))
  Octane.Main.main (library/Octane/Main.hs:(34,1)-(42,22))
```
