### ISSUE TITLE
Support version 1.22

### ISSUE THREAD

**Issue by tfausak** [tfausak/octane#58]
http://www.rocketleaguegame.com/news/2016/09/patch-notes-v1-22/

**Comment by tfausak** [comment]
Reading through the patch notes, these are the things that I think might require some work:
- Parsing macOS replays.
- Parsing Steam OS replays.
- Parsing rumble mode replays. 
- Make sure the "new" colors still use the same old values behind the scenes. 
- Adding new products, including antennas, toppers, painted items, and arenas. This shouldn't be a show stopper because the IDs will work just fine, but I'll need to regenerate the product mapping. See #25 for how to do that. 

Trading and crates don't really affect replays, so hopefully I can ignore those. However some items are only obtainable through crates, notably the new car bodies.

**Comment by tfausak** [comment]
Off to a great start! I played a short match on the new "DFH Stadium (Stormy)" map and saved the replay. When I tried to parse it, I got this error:

```
octane.EXE:
  Data.Binary.Get.runGet at position 187:
    Don't know how to read property "TAGame.GameEvent_TA:MatchTypeClass"
```

[9938DF284ACDAADE0F15028012E76A78.zip](https://github.com/tfausak/octane/files/462918/9938DF284ACDAADE0F15028012E76A78.zip)

**Comment by tfausak** [comment]
Same deal on "Urban Central (Dawn)" ([F6DD03F24C7548ABDA00FB902A42767E.zip](https://github.com/tfausak/octane/files/462924/F6DD03F24C7548ABDA00FB902A42767E.zip)) and "Octagon" ([DEC0FEE5442024DF44BED1A8A7C7CE42.zip](https://github.com/tfausak/octane/files/462925/DEC0FEE5442024DF44BED1A8A7C7CE42.zip)). Not surprising.

**Comment by tfausak** [comment]
I got a different error from a rumble replay.

```
octane.EXE:
  Data.Binary.Get.runGet at position 14:
    Could not find class for property "GameInfo_Items.GameInfo.GameInfo_Items:GameReplicationInfoArchetype"
```

[1205D96C4D819800927791820096CD49.zip](https://github.com/tfausak/octane/files/462938/1205D96C4D819800927791820096CD49.zip)

**Comment by tfausak** [comment]
> Make sure the "new" colors still use the same old values behind the scenes.

There are actually more colors now. 

![colors](https://cloud.githubusercontent.com/assets/408753/18371273/9f9eadfe-75f8-11e6-8a56-3e37c3d624a8.jpg)

**Comment by tfausak** [comment]
I think `TAGame.GameEvent_TA:MatchTypeClass` should be interpreted as a flagged int. That gets me to the next property, `TAGame.PRI_TA:ClientLoadoutsOnline`. The property name looks almost exactly the same as `TAGame.PRI_TA:ClientLoadoutOnline`, which has "loadout" instead of "loadouts". Parsing that as an online loadout does not work. I doubt it's any of the other types either.

**Comment by tfausak** [comment]
This is going to be... intricate. The rumble mode introduces a lot of new properties and property types. Those are going to take a while to figure out.

**Comment by tfausak** [comment]
The amazing @jjbott has already figured out a lot of this:
- https://github.com/jjbott/RocketLeagueReplayParser/commit/1c385d6577077dad4991957e76a0bc2bf6cbd6bf
- https://github.com/jjbott/RocketLeagueReplayParser/commit/ba72e5afe475f28d7232cb4b7076ffe9ae8bcd0e

**Comment by tfausak** [comment]
Here is a replay I saved on macOS: [00070009003B0009002300DE5E69F59F.replay.zip](https://github.com/tfausak/octane/files/463948/00070009003B0009002300DE5E69F59F.replay.zip)

I was afraid that there might be some byte-order problems, but it looks like there aren't any. It fails in the same way as the Windows replays. 

And for future reference, the replays are saved in `~/Library/Application Support/Rocket League/TAGame/Demos`

**Comment by jjbott** [comment]
> The amazing @jjbott has already figured out a lot of this

Darn right I did. :P

I know the start of WeldInfo is:
- Bit
- 32 bit id (actor id probably) (might be swapped with the above, but I don't think so)
- 3d vector (offset)
- 32 bit float (mass I think, always(?) 0.1 with normal mutators)

...then who knows what. Probably a rotation next, but any random clump of bits will look like a valid rotation vector. I have a couple test replays where the rotation should be almost the same, but I havent had luck parsing anything consistent. Plus I havent found the start of the next property. I gave up for a  bit since it was 2am and my brains fell out. :) I've barely looked at ClubColors

**Comment by tfausak** [comment]
For posterity: On my Debian machine, replays ended up in `~/.local/share/Rocket League/TAGame/Demos`. Here's a sample demo file from the Linux client: [42CFFC3011E678602A6E819636F1A041.replay.gz](https://github.com/tfausak/octane/files/466234/42CFFC3011E678602A6E819636F1A041.replay.gz)
