### ISSUE TITLE
Unprocessable replays

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/octane#6]
I've been running Octane against around half of the replays which have been uploaded to Rocket League Replays tonight. Of the ~26,000 I've tested, 105 (0.4%) came back with errors of some variety.  I've collated them below, grouped by the exception message.

`>>> octane-0.6.2-osx: don't know how to read property "Engine.Actor:Owner"`
- https://www.rocketleaguereplays.com/replays/5390/
- https://www.rocketleaguereplays.com/replays/3540/
- https://www.rocketleaguereplays.com/replays/53420/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.Actor:Base"`
- https://www.rocketleaguereplays.com/replays/29321/
- https://www.rocketleaguereplays.com/replays/7225/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.Actor:RelativeLocation"`
- https://www.rocketleaguereplays.com/replays/34030/
- https://www.rocketleaguereplays.com/replays/24364/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.TeamInfo:TeamName"`
- https://www.rocketleaguereplays.com/replays/15515/

`>>> octane-0.6.2-osx: don't know how to read property "Engine.TeamInfo:TeamIndex"`
- https://www.rocketleaguereplays.com/replays/17813/

`>>> octane-0.6.2-osx: could not find class for object id <int>`
- https://www.rocketleaguereplays.com/replays/54141/
- https://www.rocketleaguereplays.com/replays/43809/
- https://www.rocketleaguereplays.com/replays/43811/
- https://www.rocketleaguereplays.com/replays/43824/
- https://www.rocketleaguereplays.com/replays/43861/
- https://www.rocketleaguereplays.com/replays/43984/
- https://www.rocketleaguereplays.com/replays/43985/
- https://www.rocketleaguereplays.com/replays/43986/
- https://www.rocketleaguereplays.com/replays/48722/
- https://www.rocketleaguereplays.com/replays/54137/
- https://www.rocketleaguereplays.com/replays/7850/

`>>> octane-0.6.2-osx: parsing previous frame probably failed. time: 1.597e-42, delta: 2.7500482`
- https://www.rocketleaguereplays.com/replays/54859/
- https://www.rocketleaguereplays.com/replays/39988/
- https://www.rocketleaguereplays.com/replays/39992/
- https://www.rocketleaguereplays.com/replays/39833/
- https://www.rocketleaguereplays.com/replays/54859/
- https://www.rocketleaguereplays.com/replays/39996/
- https://www.rocketleaguereplays.com/replays/39994/
- https://www.rocketleaguereplays.com/replays/41001/
- https://www.rocketleaguereplays.com/replays/39991/
- https://www.rocketleaguereplays.com/replays/39990/
- https://www.rocketleaguereplays.com/replays/39989/
- https://www.rocketleaguereplays.com/replays/39987/
- https://www.rocketleaguereplays.com/replays/39993/
- https://www.rocketleaguereplays.com/replays/39860/
- https://www.rocketleaguereplays.com/replays/39088/
- https://www.rocketleaguereplays.com/replays/39087/
- https://www.rocketleaguereplays.com/replays/39862/
- https://www.rocketleaguereplays.com/replays/32791/
- https://www.rocketleaguereplays.com/replays/32792/
- https://www.rocketleaguereplays.com/replays/28619/
- https://www.rocketleaguereplays.com/replays/27199/
- https://www.rocketleaguereplays.com/replays/30546/
- https://www.rocketleaguereplays.com/replays/30818/
- https://www.rocketleaguereplays.com/replays/30822/
- https://www.rocketleaguereplays.com/replays/28560/
- https://www.rocketleaguereplays.com/replays/28167/
- https://www.rocketleaguereplays.com/replays/17993/
- https://www.rocketleaguereplays.com/replays/17995/
- https://www.rocketleaguereplays.com/replays/18000/
- https://www.rocketleaguereplays.com/replays/17998/
- https://www.rocketleaguereplays.com/replays/17999/
- https://www.rocketleaguereplays.com/replays/32658/
- https://www.rocketleaguereplays.com/replays/17899/
- https://www.rocketleaguereplays.com/replays/26470/
- https://www.rocketleaguereplays.com/replays/3070/

`>>> octane-0.6.2-osx: the unknown flag in a new replication is true! what does it mean?`
- https://www.rocketleaguereplays.com/replays/39698/
- https://www.rocketleaguereplays.com/replays/39697/
- https://www.rocketleaguereplays.com/replays/47109/
- https://www.rocketleaguereplays.com/replays/39316/
- https://www.rocketleaguereplays.com/replays/39317/
- https://www.rocketleaguereplays.com/replays/39315/
- https://www.rocketleaguereplays.com/replays/38837/
- https://www.rocketleaguereplays.com/replays/38831/
- https://www.rocketleaguereplays.com/replays/38839/
- https://www.rocketleaguereplays.com/replays/38835/
- https://www.rocketleaguereplays.com/replays/38836/
- https://www.rocketleaguereplays.com/replays/38832/
- https://www.rocketleaguereplays.com/replays/38834/
- https://www.rocketleaguereplays.com/replays/38833/
- https://www.rocketleaguereplays.com/replays/38838/
- https://www.rocketleaguereplays.com/replays/38247/
- https://www.rocketleaguereplays.com/replays/38248/
- https://www.rocketleaguereplays.com/replays/38042/
- https://www.rocketleaguereplays.com/replays/38040/
- https://www.rocketleaguereplays.com/replays/38039/
- https://www.rocketleaguereplays.com/replays/38041/
- https://www.rocketleaguereplays.com/replays/38043/
- https://www.rocketleaguereplays.com/replays/34060/
- https://www.rocketleaguereplays.com/replays/34187/
- https://www.rocketleaguereplays.com/replays/32483/
- https://www.rocketleaguereplays.com/replays/32482/
- https://www.rocketleaguereplays.com/replays/30846/
- https://www.rocketleaguereplays.com/replays/29322/
- https://www.rocketleaguereplays.com/replays/29323/
- https://www.rocketleaguereplays.com/replays/29318/
- https://www.rocketleaguereplays.com/replays/32637/
- https://www.rocketleaguereplays.com/replays/30528/
- https://www.rocketleaguereplays.com/replays/30529/
- https://www.rocketleaguereplays.com/replays/30526/
- https://www.rocketleaguereplays.com/replays/33564/
- https://www.rocketleaguereplays.com/replays/29319/
- https://www.rocketleaguereplays.com/replays/27967/
- https://www.rocketleaguereplays.com/replays/41188/
- https://www.rocketleaguereplays.com/replays/30556/
- https://www.rocketleaguereplays.com/replays/41189/
- https://www.rocketleaguereplays.com/replays/38972/
- https://www.rocketleaguereplays.com/replays/29847/
- https://www.rocketleaguereplays.com/replays/28166/
- https://www.rocketleaguereplays.com/replays/18303/
- https://www.rocketleaguereplays.com/replays/16779/
- https://www.rocketleaguereplays.com/replays/16745/
- https://www.rocketleaguereplays.com/replays/42163/
- https://www.rocketleaguereplays.com/replays/16242/
- https://www.rocketleaguereplays.com/replays/16088/
- https://www.rocketleaguereplays.com/replays/16046/

**Comment by tfausak** [comment]
Wow, this is excellent! Thanks for the report. I'll start trying to figure these out.

**Comment by tfausak** [comment]
Does PyRope parse these replays correctly?

**Comment by danielsamuels** [comment]
From testing the first couple of replays in each block, the answer appears to be 'no'.

**Comment by tfausak** [comment]
#7 fixed some of these, but not all.

**Comment by tfausak** [comment]
Of the replays that I can't parse, _most_ of them are seasonal. I assume the oddball team names, logos, and colors are replicated. (Edit: But I can parse _some_ seasonal replays, so that doesn't really explain it.) 

However some of them aren't seasonal:

| ID | v1 | v2 | Date |
| --- | --- | --- | --- |
| [f926e80e4d8ed9f1fb5c7bb0f6adef63](https://www.rocketleaguereplays.com/replays/f926e80e-4d8e-d9f1-fb5c-7bb0f6adef63/) | 867 | 9 | 2015-08-23:19-46 |
| [91f28b33459bf6353895ac90a79e6f74](https://www.rocketleaguereplays.com/replays/91f28b33-459b-f635-3895-ac90a79e6f74/) | 867 | 9 | 2015-09-08:04-08 |
| [b03edb7047dca8235f01d6ba679e073a](https://www.rocketleaguereplays.com/replays/b03edb70-47dc-a823-5f01-d6ba679e073a/) | 867 | 9 | 2015-11-06:15-50 |
| [387f059c47c09e253c875ca990efd9f2](https://www.rocketleaguereplays.com/replays/387f059c-47c0-9e25-3c87-5ca990efd9f2/) | 868 | 10 | 2015-11-16:01-45 |
| [8a6ca8c8416464e56e50e4a06737d60c](https://www.rocketleaguereplays.com/replays/8a6ca8c8-4164-64e5-6e50-e4a06737d60c/) | 868 | 10 | 2015-11-24:00-49 |
| [589865e84f5dcc5280e323ae6a9f0748](https://www.rocketleaguereplays.com/replays/589865e8-4f5d-cc52-80e3-23ae6a9f0748/) | 868 | 10 | 2016-01-02:01-02 |
| [cf8bf697406617a76631039371e59efc](https://www.rocketleaguereplays.com/replays/cf8bf697-4066-17a7-6631-039371e59efc/) | 868 | 11 | 2016-06-02:16-42 |

**Comment by tfausak** [comment]
For those replays, my current best guess is that I'm parsing `Engine.Actor:RelativeRotation` incorrectly. The last or second-to-last property read before failing is always that.

```
f926e80e4d8ed9f1fb5c7bb0f6adef63
property "Engine.Actor:bHidden" => PBoolean True
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = -0.687521, vectorZ = -0.20877713})
property "Engine.Actor:Owner" => PFlaggedInt True 305605058
octane: parsing previous frame probably failed. time: -5.945398e-25, delta: 3.549442e31

91f28b33459bf6353895ac90a79e6f74
property "Engine.Actor:bHidden" => PBoolean True
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = -0.9375286, vectorZ = 0.338023})
property "Engine.Actor:RelativeLocation" => PLocation (Vector {vectorX = 5389, vectorY = 13669, vectorZ = -20283})
octane: don't know how to read property "Engine.Actor:Instigator"

b03edb7047dca8235f01d6ba679e073a
property "Engine.Actor:bHidden" => PBoolean True
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = 0.31250954, vectorZ = 0.83819085})
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -0.36481827, vectorY = -9.00296e-3, vectorZ = -0.9816279})
octane: don't know how to read property "Engine.TeamInfo:TeamName"

387f059c47c09e253c875ca990efd9f2
property "TAGame.Vehicle_TA:ReplicatedThrottle" => PByte 252
property "Engine.Actor:bHidden" => PBoolean True
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = -0.56251717, vectorZ = 0.8537553})
octane: parsing previous frame probably failed. time: -3.1161744e38, delta: 0.23862033

8a6ca8c8416464e56e50e4a06737d60c
property "Engine.Actor:bHidden" => PBoolean True
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = -0.687521, vectorZ = -0.20868556})
property "Engine.Actor:Owner" => PFlaggedInt True 1815984885
octane: parsing previous frame probably failed. time: -6.693973e19, delta: -9.109149e-38

589865e84f5dcc5280e323ae6a9f0748
property "Engine.Actor:bHidden" => PBoolean True
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = 0.31250954, vectorZ = -0.2088992})
property "Engine.Actor:bProjTarget" => PBoolean False
octane: don't know how to read property "Engine.Actor:Base"

cf8bf697406617a76631039371e59efc
property "Engine.Actor:bHidden" => PBoolean True
property "Engine.Actor:RelativeRotation" => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = -6.250191e-2, vectorZ = -0.19333476})
property "Engine.Actor:bProjTarget" => PBoolean True
octane: parsing previous frame probably failed. time: 6.93815e-28, delta: -8.825149e-29
```

**Comment by danielsamuels** [comment]
Looking at the [Unreal Source code](https://github.com/EpicGames/UnrealEngine/blob/ab237f46dc0eee40263acbacbe938312eb0dffbb/Engine/Source/Runtime/Core/Public/Math/Rotator.h#L11) it looks like it's just a triple float, but I know from my experience on PyRope that it never seemed to work.  I'm not entirely sure what else it would be.

**Comment by danielsamuels** [comment]
Looking at an older commit, it looks like I ended up [reading a boolean then the 3 floats](https://github.com/Galile0/pyrope/pull/13/commits/31ea902294362205fa5e6ac9323af708005f41e3). Perhaps that might be worth a try?

**Comment by tfausak** [comment]
Thanks for the tip! Reading a boolean before the relative rotation fixes one of the replays (91f…) but not the rest. 

I also tried reading the flag, then using that to decide if I should read the vector or not. That worked for two replays (the one above and 589…), but not the rest.

**Comment by tfausak** [comment]
Looking at [the rotator file](https://github.com/EpicGames/UnrealEngine/blob/master/Engine/Source/Runtime/Core/Public/Math/Rotator.h), there are few serialization methods: `SerializeCompressed`, `SerializeCompressedShort`, and `NetSerialize`. So maybe it is serialized differently depending on something about the values in it? 

Similarly there are a couple vector serialization methods in [the net serialization file](https://github.com/EpicGames/UnrealEngine/blob/master/Engine/Source/Runtime/Engine/Classes/Engine/NetSerialization.h): `SerializePackedVector` and `SerializeFixedVector`. 

I'm not sure what to make of all that, but there you go.

**Comment by danielsamuels** [comment]
I've been doing some more research.  According to UE Explorer, `Actor.RelativeRotation` is defined like this: `const Rotator RelativeRotation`. `Rotator` is defined as being `Core.Object.Rotator`.  According to [this page](http://www.codekisk.com/unreal/ut3/scriptref/core/object.html#_Rotator), Rotator (in UT3 at least) is a struct of three _integers_ - not floats.  Remember that Rocket League is written in Unreal Engine 3, not 4.  No note on a flag though.

**Comment by tfausak** [comment]
Interesting! I'll try parsing rotators as 3 integers. Hopefully that works. 

One the topic of seasonal replays, the team replication information looks like this:

``` json
{
    "state": "existing",
    "object_name": "Archetypes.Teams.Team0",
    "initialization": null,
    "class_name": "TAGame.Team_TA",
    "actor_id": 5,
    "properties": {
        "TAGame.Team_TA:GameEvent": {
            "tag": "PFlaggedInt",
            "contents": [
                true,
                4
            ]
        },
        "TAGame.Team_TA:LogoData": {
            "tag": "PFlaggedInt",
            "contents": [
                true,
                124
            ]
        },
        "TAGame.Team_TA:CustomTeamName": {
            "tag": "PString",
            "contents": "Dragons"
        }
    }
},
```

I'm not sure what the game event property means, but the others are straightforward. Looks like the colors are not part of the team information. I think the colors for the stadium and scoreboard are implied from the logo choice. The colors for the car are given (as usual) in the car's team paint property.

``` json
"TAGame.Car_TA:TeamPaint": {
    "tag": "PTeamPaint",
    "contents": [
        1,
        0,
        0,
        270,
        270
    ]
},
```

**Comment by tfausak** [comment]
Reading 32-bit integers parses 91f... and 589... correctly, but none of the others. Parsing them as 32-bit compressed integers did the same thing. Same with parsing them as 8-bit integers. It doesn't really make sense that I can parse an arbitrary number of bits and have the whole thing succeed.

Maybe there's a reference to another actor in there? This is a _relative_ rotation, after all. Maybe you're supposed to read an actor ID before the vector...

**Comment by tfausak** [comment]
I'm going to stop looking at this for now. I would love to be able to parse every replay, but I'm not having much luck figuring this out. Considering this is a tiny fraction of all replays (less than 100 out of more than 25,000), it's safe to say it doesn't happen that often. 

Maybe @jjbott can figure it out :smiley:

**Comment by phillijw** [comment]
@jjbott is a somewhat of a superstar. He's got this

**Comment by jjbott** [comment]
lol, shush you. :P

**Comment by rustyfausak** [comment]
[This wiki page about rotators in ue3](https://wiki.beyondunreal.com/Legacy:Rotator) says that the values range from 0-65536. Have you tried reading 16 bits for each rotator part (pitch, yaw, roll)?

**Comment by rustyfausak** [comment]
Actually further reading that wiki page:

> Wormbo: Rotators are already compressed for replication. For each component only 1 or 9 bits are replicated. The first bit signals, whether the component is zero and if it isn't, a byte with the value follows. That byte is calculated as Roll in the CompressExample function above. The (De)CompressExample functions are very handy though, if full precision is required for a rotation direction.

and 

> Before a rotator is replicated, its component values are compressed into the range of a byte through the function ((value >> 8) & 0xFF). This has the advantage that a rotator only takes up 3 bytes of bandwidth for its value, but also limits the precision to 256 possible values per component. That's why a player's view rotation is generally not replicated as a rotator. The reduced Yaw and Pitch precision would hurt aiming accuracy.

**Comment by jjbott** [comment]
Shot in the dark, have any of the weird ones been loaded into RL to see if they actually work? Its possible a small number are actually corrupt. That's wishful thinking though. I'd check but I'm at work and _definitely_ not parsing RL replays, no sir.

Also, every time I've run across "Engine.Actor:RelativeRotation" it meant that the parser was lost and reading garbage. So it might be a red herring. I haven't seen it yet though (or my commit fixed it and I forgot I saw it), so not sure

**Comment by tfausak** [comment]
It may be reading garbage by that point. From what I remember, most of the previous properties looked like they made sense. But maybe I wasn't looking far enough back. 

Loading the replays into Rocket League is a good sanity check. I would be surprised if they were actually corrupt, but who knows!

Reading 1 or 9 bits for each component is how [the rotation is serialized in the class initialization](https://github.com/tfausak/octane/blob/1291d5b8ea423b9923c2d30a6e4db0e608cb70ee/library/Octane/Parser.hs#L793). It would make sense to do the same thing for relative rotations.

**Comment by tfausak** [comment]
Rocket League can load and view all 7 of those replays without issue. I didn't notice any commonalities between them.

**Comment by tfausak** [comment]
Looking at replay 387..., these are the last 3 frames it successfully parsed:

```
Frame at 462.37 (+0.06)
Frame at 462.43 (+0.06)
 Replication for 7... open? True
  Engine.PlayerReplicationInfo:Ping (30 / 76)
    => PByte 42
  TAGame.PRI_TA:MatchShots (54 / 76)
    => PInt 1
 Replication for 222... open? True
  TAGame.Vehicle_TA:ReplicatedThrottle (54 / 58)
    => PByte 252
Frame at 462.49 (+0.06)
 Replication for 18... open? True
  Engine.Actor:bHidden (11 / 26)
    => PBoolean True
  Engine.Actor:RelativeRotation (0 / 26)
    => PRelativeRotation (Vector {vectorX = -1.0000305, vectorY = -0.56251717, vectorZ = 0.8537553})
```

That looks ok in isolation, but when you compare it against literally every other replication for actor 18...

```
 Replication for 18... open? True
  Engine.TeamInfo:Score (22 / 26)
    => PInt 5
  TAGame.Team_TA:GameEvent (26 / 26)
    => PFlaggedInt True 8
```

Looks like @jjbott may be right: The parser is just reading garbage. It thinks it should be reading this hidden boolean property, but really it should be reading the team's score. 

The other 6 replays all have the same problem. What are the odds of an off-by-eleven error? 

Edited to add: 11 would be stored as `0b1101`. 22 would be stored as `0b01101`. So I think there's a bit missing at the beginning.

**Comment by jjbott** [comment]
For the 7 replays in https://github.com/tfausak/octane/issues/6#issuecomment-224163942 , I had problems with at least some of them, but after my commit this morning they're all fine. The main issue was that TAGame.Team_TA isn't the right class to use for teams. Amazing how often it works though.

I havent downloaded all the replays yet, but so far I'm only having trouble with 3 of them:

Found that B82DDB624C393A4A425E68AB40DC2450 (https://www.rocketleaguereplays.com/replays/7850/) loads into RL and plays fine, but crashes at the end of the match. Neat! Makes sense, the last couple properties in the last frame seem to be gibberish that ends with a ton of 0 bytes

FDC79DA84DD463D4BCCE6B892829AC88 has an actor state at time 218.9339 that looks like this:

```
    ActorState: Id 25 State Existing
    TypeID: 151 (TAGame.Default__PRI_TA)
    Property: ID 30 Name Engine.PlayerReplicationInfo:Ping
    Data: 9
    Property: ID 39 Name TAGame.PRI_TA:PartyLeader
    Data: Unknown DCE46B13
    Property: ID 30 Name Engine.PlayerReplicationInfo:Ping
    Data: 213
    Property: ID 7 Name Engine.Actor:bCollideWorld
    Data: True
```

I parse it fine, but the parser gets lost after reading it. 2 obvious issues: Ping is in the state twice, and the PartyLeader has an Unknown type and an id that isn't 0. Something in that neighborhood is super mad.

C7BEF4BA40F61CDC1C2E0F9C1C0733DB has an actor state in the very first frame that I parse as

```
    ActorState: Id 5 State Existing
    TypeID: 196 (Archetypes.GameEvent.GameEvent_Season:CarArchetype)
    Property: ID 62 Name TAGame.PRI_TA:MatchGoals
    Data: 1
    Property: ID 50 Name TAGame.PRI_TA:ReplicatedGameEvent
    Data: { Active = False, ActorId = -939392980 }
    Incomplete!
```

Theres no one who has 1 goal at the start of the match, and there certainly isnt an ActorId -939392980. It then gets stuck. Everything before this actor state seems fine. I sort of suspect a wrong class thats causing the wrong properties to be parsed out, but who knows.

**Comment by rustyfausak** [comment]
> Amazing how often it works though.

i've thought this many times after finding random huge bugs in parsing replays..

**Comment by tfausak** [comment]
Great find @jjbott! Making those changes to Octane fixed the parsing of those 7 replays. At least in terms of reading the correct number of bits.

**Comment by tfausak** [comment]
@jjbott: For replay FDC79DA84DD463D4BCCE6B892829AC88, you need special handling for the party leader property. This is how Octane parses that replication:

``` json
                {
                    "actor_id": 25,
                    "class_name": "TAGame.PRI_TA",
                    "initialization": null,
                    "object_name": "TAGame.Default__PRI_TA",
                    "properties": {
                        "Engine.PlayerReplicationInfo:Ping": {
                            "contents": 9,
                            "tag": "PByte"
                        },
                        "TAGame.PRI_TA:PartyLeader": {
                            "contents": [
                                0,
                                {
                                    "contents": null,
                                    "tag": "SplitscreenId"
                                },
                                null
                            ],
                            "tag": "PUniqueId"
                        }
                    },
                    "state": "existing"
                }
```

I fixed this in 8a068f156e7a3c0d8693ad59be99a4ba6312f324. If you're reading a party leader and the system ID (the first integer) is 0, then you're done. There's no more information to read. You can also see [how PyRope does it](https://github.com/rocket-league-replays/pyrope/blob/086267594c0dc9fa51316118adc07011f9c018ec/pyrope/netstream_property_parsing.py#L181-L185), which requires backtracking.

**Comment by jjbott** [comment]
@tfausak Huh neat. That was actually one of the things I was thinking about (stopping after reading a 0), but again, the existing code has never failed before so I trusted it

**Comment by tfausak** [comment]
I'm pretty sure I figured it out. I was able to parse all of the reported bad replays without messing up any good replays. The problem was that the `Archetypes.GameEvent.GameEvent_Season:CarArchetype` object looks like it should map to the `TAGame.Car_Season_TA` class, but it actually maps to the `TAGame.Car_TA` class.

**Comment by jjbott** [comment]
@tfausak Nice! Yeah that was on my list as well, but the RL code definitely seems to suggest that TAGame.Car_Season_TA is correct. It parsed so badly that it had to be wrong...

**Completely** unrelated...  Not sure if anyone is interested in trying to standardize JSON output, but I've put a lot of work into tightening up JSON output over the last 6 months or so and mine looks completely different. Here is [my JSON for that frame in FDC7](http://pastebin.com/3wDbqvfr). An example of a full replay is on my slow ass webserver at http://bunkmonkey.com:97/data/replays/817A479A475AF16E2D1E8E8138452FBA.replay.json .  That's from my JSON serializer that tries to get rid of as much duplicate data as it can. It could still be compressed further, but I think it strikes a nice balance between readability and file size.

**Comment by tfausak** [comment]
Your JSON looks way better. Mine is pretty much the minimum required to debug the data at this point. 

:point_right: #9
