### ISSUE TITLE
Attempting to understand Xbox IDs

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/octane#66]
Hello,

I've been looking to do a little more with non-steam profiles, and more specifically with Xbox profiles.  I'm looking at the replay data for [this replay](https://www.rocketleaguereplays.com/replays/bcdd1913-497a-0929-4415-2a918b18e60b/) and I'm seeing Xbox data which looks like this: 

```
"Engine.PlayerReplicationInfo:UniqueId": {
    "Value": {
        "Remote": {
            "Value": 2533274872181390,
            "Type": "Xbox"
        },
        "Local": 0,
        "System": "Xbox"
    },
    "Type": "UniqueId"
},
```

Looking at the data across [a wider dataset](https://gist.github.com/danielsamuels/a6a83378f168b36e3282b1003d2a7f15) (ignore the first 3 columns), you can see that there's clearly some sort of pattern.  It's my understanding that Xbox profiles work with gamer tags, which are text strings. What I'm trying to determine is how one would go from these numeric values to the gamertag. Are these perhaps some sort of underlying IDs which need to perhaps be looked up and converted into text strings?

I realise this may be out of scope for this project, but it could be that more meaningful data could be returned for these specific ID types.

**Comment by danielsamuels** [comment]
I've done some research into this.  These values are known as XUIDs (Xbox Account User ID).  Using the API from xboxapi.com I was able to convert this particular XUID into the gamertag of 'Roxoxx', looking at the page on RLR you can see that this value appears to be correct.  One thing I'm now wondering is if the player name is always the gamer tag - if it is, then I don't need to do any conversions from XUID to gamer tag, I can just use the player name.

I don't think this is going to be something that you can really convert with Octane, so I'm going to close this issue.

**Comment by tfausak** [comment]
:+1:
