### ISSUE TITLE
Don't know how to read property "TAGame.GameEvent_Soccar_TA:GameTime"

### ISSUE THREAD

**Issue by ghost** [tfausak/octane#69]
Edit: worth noting that this is a 20 minute replay!

Replay file triggering the error:
[1v1_steerthrottleonly.replay.zip](https://github.com/tfausak/octane/files/613964/1v1_steerthrottleonly.replay.zip)
The replay was recorded on the current build in Linux, using the latest release of Octane.
Full error:
`Data.Binary.Get.runGet at position 199: Don't know how to read property "TAGame.GameEvent_Soccar_TA:GameTime"
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get`

(PS Thank you so much for this project! Its existence has saved me a hell of a lot of trouble!)

**Comment by tfausak** [comment]
Thanks for the report! Sorry Octane didn't work for this replay. This should be a simple fix.

**Comment by tfausak** [comment]
TIL you can close issues across repositories. This isn't actually fixed in Octane yet.
