### ISSUE TITLE
New version of Rocket League breaks octane.exe

### ISSUE THREAD

**Issue by jonoomph** [tfausak/octane#70]
Just recorded a replay file with the new version of Rocket League, and get this error from octane.exe:

`Data.Binary.Get.runGet at position 161: could not get attribute map for CompressedWord {compressedWordLimit = 1023, compressedWordValue = 896}\nCallStack (from HasCallStack):\n  error, called at libraries\\binary\\src\\Data\\Binary\\Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get\n`

**Comment by jonoomph** [comment]
Here is the replay file
[15ECDB254B458C7D39BB2CA182C6F5F6.zip](https://github.com/tfausak/octane/files/638096/15ECDB254B458C7D39BB2CA182C6F5F6.zip)

**Comment by tfausak** [comment]
Thanks for reporting this! Unfortunately Psyonix changed the replay format slightly in the latest patch (version 1.25, aka "Starbase ARC"). These days Octane is a wrapper around Rattletrap, which does all the hard work. I'm trying to figure out how to parse these new replays over here: https://github.com/tfausak/rattletrap/issues/19

**Comment by danielsamuels** [comment]
With rattletrap now working, would it be possible to get a new Octane release please?

**Comment by tfausak** [comment]
Absolutely! It's the first thing on my to-do list today.

**Comment by danielsamuels** [comment]
Awesome, thank you!

**Comment by tfausak** [comment]
This should be fixed by 87f9c1b44f0d2ad178b92e0c5179f1d2e9103e1e. Once the build completes I'll release a new version.

**Comment by tfausak** [comment]
Should be available in [0.18.0](https://github.com/tfausak/octane/releases/tag/0.18.0) once the builds finish. Thanks again for reporting this!
