### ISSUE TITLE
After the new RL Update Error with Octane.exe on Windows

### ISSUE THREAD

**Issue by miesmacher** [tfausak/octane#74]
C:\rl_proj>octane.exe < C67C590740452762CF72C89DC13202B2.replay > test.json
octane.exe: Data.Binary.Get.runGet at position 1116: could not get name for index Word32 {word32Value = 562168010}
CallStack (from HasCallStack):
  error, called at libraries\binary\src\Data\Binary\Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get

**Comment by tfausak** [comment]
Ah, yup. Patch 1.37 changed some stuff. I updated [Rattletrap](https://github.com/tfausak/rattletrap), which Octane uses, but haven't updated Octane itself yet. I'll take a look soon, but try using Rattletrap in the meantime.

**Comment by tfausak** [comment]
Have you had any luck using Rattletrap? At this point rocketleaguereplays.com has moved off of Octane, so I'd like to deprecate it.

**Comment by miesmacher** [comment]
Hey, i used Rattletrap for Windows but it seems like that the output json has a different format than the one from octane. I was to lazy to inspect the json and change my code while hoping octane gets updated. 

If you discontinue octance i think i have to use  rattletrap.

**Comment by tfausak** [comment]
Yes, Rattletrap's output is a little different than Octane's. 

I'll try to upgrade Octane to support the latest patch.
